INSERT INTO contact (FIRST_NAME, LAST_NAME, BIRTH_DATE) VALUES ('James', 'Carter', '1981-01-03');
INSERT INTO contact (FIRST_NAME, LAST_NAME, BIRTH_DATE) VALUES ('Helen', 'Leary', '1982-02-04');
INSERT INTO contact (FIRST_NAME, LAST_NAME, BIRTH_DATE) VALUES ('Linda', 'Douglas', '1983-03-05');
INSERT INTO contact (FIRST_NAME, LAST_NAME, BIRTH_DATE) VALUES ('Rafael', 'Ortega', '1984-04-06');
INSERT INTO contact (FIRST_NAME, LAST_NAME, BIRTH_DATE) VALUES ('Henry', 'Stevens', '1985-05-07');
INSERT INTO contact (FIRST_NAME, LAST_NAME, BIRTH_DATE) VALUES ('Sharon', 'Jenkins', '1986-06-13');
